blog/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name = 'blog'

urlpatterns = [
    path('', render_posts, name='post'),
    path('<int:post_id>', post_detail, name='post_detail')
]

direct_web/urls.py
from django.contrib import admin
from django.urls import path, include
from portfolio import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime

class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=2500)
    image = models.ImageField(upload_to='blog/images')
    date = models.DateField(datetime.date.today)

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField

class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to='portfolio/images/')
    url = URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

def render_posts(request):
    post = Post.objects.all()
    return render(request, 'post.html', {'post': post})

def post_detail(request, post_id):
    post_id = get_object_or_404(Post, pk=post_id)
    return render(request, 'post_detail.html', {"post":post_id})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def index(request):
    projects = Project.objects.all()
    return render(request, 'index.html', {'projects':projects})

blog/templates/post.html
{% extends 'layout.html' %}

{% block content %}

<h1 class="fs-2">Posts</h1>

{% for post in post %}

<div class="py-3">
    <div class="card card-body bg-black">
        <div class="row">
            <div class="col-3">
                <img class="img-fluid" src="{{post.image.url}}" alt="{{post.title}}">
            </div>
            <div class="col-9">
                <h1>{{post.title}}</h1>
                <p>{{post.description|striptags|truncatechars:10}}</p>
                <p>{{post.date|date:'M d Y'|upper}}</p>
                <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary">{{post.title}}</a>
            </div>
        </div>
    </div>
</div>

{% endfor %}

{% endblock %}

blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}

<div class="text-center">
    <h2>{{post.title}}</h2>
    <h3 class="my-2 h5 text-muted">{{post.date|date:'F jS Y'}}</h3>

    <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid"> 

    <div class="my-4">
        <p>{{post.description|safe}}</p>
    </div>

</div>

{% endblock %}

portfolio/templates/index.html
{% extends 'layout.html' %}

{% block content %}

{% load static %}

<header class="row bg-black">
    <div class="col-md-4" >
        <img src="{% static 'portfolio/profile_v2.png' %}" style="margin:10px; border-radius: 15px;">
    </div>
    <div class="col-md-8 my-auto">
        <h1>Hi! I am @elektxo</h1>
        <h3>I'm a Python FullStack Developer</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium iure natus quam officia nulla tenetur, asperiores earum, nihil debitis maxime laboriosam repellendus alias. Minima aliquid iure dicta molestiae illo ut.
        Itaque, laudantium fuga. Ducimus et labore natus at consectetur tempore nemo repellendus, molestias fugiat, quo voluptatum inventore cupiditate quisquam porro itaque aliquid, nobis voluptatibus dolores neque consequatur modi enim pariatur.
        Error non ratione, facere harum maiores magnam repudiandae sint. Temporibus hic consequuntur suscipit reprehenderit totam iusto eos. Dolorum atque dolor vitae minus facilis esse laboriosam dolore, sunt necessitatibus nam incidunt!
        Magnam rem non earum perspiciatis sed repellendus minima voluptatem harum illo voluptatum! Tenetur, velit. Nisi dicta cumque ut laboriosam sapiente alias quis fuga odio modi natus. Error dicta fuga eligendi?
        Ratione qui necessitatibus labore commodi officia cumque obcaecati repellat eos. Provident, atque! Eligendi quibusdam amet recusandae cum minus architecto perferendis optio explicabo suscipit non in voluptas, eum voluptatum reiciendis error.
        Eligendi laboriosam sit facilis nemo fugit odio aut, eveniet suscipit itaque aliquid perferendis illum illo ad iusto officiis ea aliquam. Iusto ea odio exercitationem possimus et, excepturi quo cupiditate praesentium.</p>
    </div>
</header>

<div class="row my-4 text-center">

    <h3>My Projects</h3>
    <p>Welcome to my work area</p>

    {% for project in projects %}

<div class="col-md-4 p-4">
    <div class="card bg-black card-project">
        <div class="card-body">
                    
            <h2>{{project.title}}</h2>
            <p>{{project.description}}</p>
            <img src="{{project.image.url}}" alt="{{project.title}}" class="img-fluid" />
            {% if project.url %}
            <a href="{{project.url}}" class="btn btn-light rounded-0 btn-sm" target="_blank">Project page</a>
            {% endif %}

        </div>
    </div>
</div>

    {% endfor %}

    {% endblock %}
</div>

portfolio/templates/layout.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="author" content="@elektxo">
    <link rel="shortcut icon" href="{% static 'portfolio/dev3.ico' %}" type="image/x-icon">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dev by elektxo</title>
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
</head>
<body id="body" class="text-light">
    {% include 'partials/navbar.html' %}

    <div class="container p-4">
    {% block content %}
    {% endblock %}
    </div>

    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
            <a href="/">
                <div class="bi">
                    <img src="{% static 'portfolio/logo.png' %}"  width="40" height="40">
                </div>
            </a>
            <span class="text-muted">Dev by @elektxo</span>    
        </div>
        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
            <li class="ms-3">
                <a class="text-muted" href="https://www.twitter.com/fuentes_ftw" target="_blank">
                    <div class="bi">
                        <img src="{% static 'portfolio/twitter.png' %}" width="40" height="40">
                    </div>
                </a>
            </li>
            <li class="ms-3">
                <a class="text-muted" href="https://www.instagram.com/fuentes_ftw" target="_blank">
                    <div class="bi">
                        <img src="{% static 'portfolio/instagram.png' %}" width="40" height="40">
                    </div>
                </a>
            </li>
        </ul>
    </footer>
</body>
</html>

portfolio/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand fw-bold fst-italic" href="/">Dev</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:post' %}">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#" disabled>Direct</a>
                </li>
            </ul>
        </div>
    </div>
</nav>